msrv = "1.74.0"

allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true

avoid-breaking-exported-api = false
standard-macro-braces = [
    { name = "format", brace = "(" },
    { name = "format_args", brace = "(" },
    { name = "vec", brace = "[" },
    { name = "matches", brace = "(" },
]

disallowed-names = ["foo", "bar", "baz", "quux", "tmp", "temp", "test"]
cognitive-complexity-threshold = 30
single-char-binding-names-threshold = 4
too-many-lines-threshold = 400
too-many-arguments-threshold = 7
type-complexity-threshold = 250
literal-representation-threshold = 16
enum-variant-name-threshold = 3
struct-field-name-threshold = 3
max-trait-bounds = 3
unreadable-literal-lint-fractions = false